version: '3.8'

services:
  grievance-anonymizer:
    build:
      context: .
      dockerfile: Dockerfile
    image: datakaveri/grievance-data-anonymization:latest
    container_name: grievance-anonymizer
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
      - NER_CORPUS_BATCH_SIZE=256
      - NER_TENSOR_BATCH_SIZE=0
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./output:/app/output
      - ./work:/app/work
    restart: "no"
